// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5GiucXTzkDvjBWqZ4TtoFnNd7EZZh1Y',
    appId: '1:825194586192:web:04d9959f7d05ee0e14f155',
    messagingSenderId: '825194586192',
    projectId: 'flutix-bf4f4',
    authDomain: 'flutix-bf4f4.firebaseapp.com',
    storageBucket: 'flutix-bf4f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRk1aD2eR_nFMdSpvPMzEiEVp1LBvljPg',
    appId: '1:825194586192:android:f58f7bc69276681414f155',
    messagingSenderId: '825194586192',
    projectId: 'flutix-bf4f4',
    storageBucket: 'flutix-bf4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0N_q6kyStfv31tHoEcdoMiKgcwuClfyM',
    appId: '1:825194586192:ios:a0dd1fb66cf62ad114f155',
    messagingSenderId: '825194586192',
    projectId: 'flutix-bf4f4',
    storageBucket: 'flutix-bf4f4.appspot.com',
    iosBundleId: 'com.example.flutix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0N_q6kyStfv31tHoEcdoMiKgcwuClfyM',
    appId: '1:825194586192:ios:189d87fa8217a27f14f155',
    messagingSenderId: '825194586192',
    projectId: 'flutix-bf4f4',
    storageBucket: 'flutix-bf4f4.appspot.com',
    iosBundleId: 'com.example.flutix.RunnerTests',
  );
}
