// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBquI3YokCj8L_QI6J5Zu-Qm5MvQti0LsE',
    appId: '1:470314519606:web:12d774143c41fa589ddc97',
    messagingSenderId: '470314519606',
    projectId: 'fluttix-db300',
    authDomain: 'fluttix-db300.firebaseapp.com',
    storageBucket: 'fluttix-db300.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbBlyGwKOPFy9zYf9FlTo6SqCPeEUYImI',
    appId: '1:470314519606:android:da963b6cd93bf2049ddc97',
    messagingSenderId: '470314519606',
    projectId: 'fluttix-db300',
    storageBucket: 'fluttix-db300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7P64YNyn4IjgZ5WmjICdXL44pxYwyv1s',
    appId: '1:470314519606:ios:69b7558986dba6b79ddc97',
    messagingSenderId: '470314519606',
    projectId: 'fluttix-db300',
    storageBucket: 'fluttix-db300.appspot.com',
    iosBundleId: 'com.example.flutix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7P64YNyn4IjgZ5WmjICdXL44pxYwyv1s',
    appId: '1:470314519606:ios:2928f52d0ded365e9ddc97',
    messagingSenderId: '470314519606',
    projectId: 'fluttix-db300',
    storageBucket: 'fluttix-db300.appspot.com',
    iosBundleId: 'com.example.flutix.RunnerTests',
  );
}
